//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SerengetiPark
//  @ File Name : GPS.java
//  @ Date : 03/04/2020
//  @ Author : mmjon 
//
//
package SerengetiPark;
/**
 * Used to express the position of an object
 * @author mmjon
 *
 */
public class GPS {
	//Attributes
	private double longitude;
	private double latitude;
	/**
	 * Constructor of GPS class
	 * @param latitude, latitude of the position
	 * @param longitude, longitude of the position
	 */
	public GPS (double latitude, double longitude) {
		this.latitude=latitude;
		this.longitude=longitude;
	}
	/**
	 * Method used to calculate the distance between two geographical positions
	 * @param pGPS, additional GPS object containing the second geographical position
	 * @return distance between the two position expressed in kilometers
	 */
	public double distanceTo(GPS pGPS){
		return Math.sqrt(Math.pow(this.longitude-pGPS.longitude,2)+Math.pow(this.latitude-pGPS.latitude,2))*85;
	}
	/**
	 * Getter of the attribute longitude 
	 * @return value of longitude
	 */
	public double getLongitude() {
		return longitude;
	}
	/**
	 * Getter of the attribute latitude
	 * @return value of latitude
	 */
	public double getLatitude(){
		return latitude;
	}
	/**
	 * Setter of the attribute longitude
	 * @param longitude, value that is wished to be set for longitude parameter
	 */
	public void setLongitude(double longitude){
		this.longitude=longitude;
	}
	/**
	 * Setter of the attribute latitude
	 * @param latitude, value that is wished to be set for latitude parameter 
	 */
	public void setLatitude(double latitude) {
		this.latitude=latitude;
	}
	
	@Override
	public String toString(){
		return "Latitude:"+" "+ latitude+","+" "+"Longitude:"+" "+longitude;
		}
}
